package com.webservice.client;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "MyServerStart", targetNamespace = "http://server.webservice.com/")
@XmlSeeAlso({ ObjectFactory.class })
public interface MyServerStart {

	/**
     * 
     */
	@WebMethod
	@RequestWrapper(localName = "testMyServerStart", targetNamespace = "http://server.webservice.com/", className = "com.webservice.client.TestMyServerStart")
	@ResponseWrapper(localName = "testMyServerStartResponse", targetNamespace = "http://server.webservice.com/", className = "com.webservice.client.TestMyServerStartResponse")
	@Action(input = "http://server.webservice.com/MyServerStart/testMyServerStartRequest", output = "http://server.webservice.com/MyServerStart/testMyServerStartResponse")
	public void testMyServerStart();

}
