package com.webservice.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "MyServerStartService", targetNamespace = "http://server.webservice.com/", wsdlLocation = "http://127.0.0.1:12580/WebService/StartMyServer?wsdl")
public class MyServerStartService extends Service {

	private final static URL MYSERVERSTARTSERVICE_WSDL_LOCATION;
	private final static WebServiceException MYSERVERSTARTSERVICE_EXCEPTION;
	private final static QName MYSERVERSTARTSERVICE_QNAME = new QName("http://server.webservice.com/", "MyServerStartService");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL("http://127.0.0.1:12580/WebService/StartMyServer?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		MYSERVERSTARTSERVICE_WSDL_LOCATION = url;
		MYSERVERSTARTSERVICE_EXCEPTION = e;
	}

	public MyServerStartService() {
		super(__getWsdlLocation(), MYSERVERSTARTSERVICE_QNAME);
	}

	public MyServerStartService(WebServiceFeature... features) {
		super(__getWsdlLocation(), MYSERVERSTARTSERVICE_QNAME, features);
	}

	public MyServerStartService(URL wsdlLocation) {
		super(wsdlLocation, MYSERVERSTARTSERVICE_QNAME);
	}

	public MyServerStartService(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, MYSERVERSTARTSERVICE_QNAME, features);
	}

	public MyServerStartService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MyServerStartService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	/**
	 * 
	 * @return returns MyServerStart
	 */
	@WebEndpoint(name = "MyServerStartPort")
	public MyServerStart getMyServerStartPort() {
		return super.getPort(new QName("http://server.webservice.com/", "MyServerStartPort"), MyServerStart.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns MyServerStart
	 */
	@WebEndpoint(name = "MyServerStartPort")
	public MyServerStart getMyServerStartPort(WebServiceFeature... features) {
		return super.getPort(new QName("http://server.webservice.com/", "MyServerStartPort"), MyServerStart.class, features);
	}

	private static URL __getWsdlLocation() {
		if (MYSERVERSTARTSERVICE_EXCEPTION != null) {
			throw MYSERVERSTARTSERVICE_EXCEPTION;
		}
		return MYSERVERSTARTSERVICE_WSDL_LOCATION;
	}

}
